[tools]
rojo = { source = "rojo-rbx/rojo", version = "7" }
selene = { source = "kampfkarren/selene", version = "*" }
stylua = { source = "JohnnyMorganz/StyLua", version = "*" }
wally = { source = "UpliftGames/wally", version = "0.3" }
